title: Bypaseando mis limitaciones
description: El blog se centra en el aprendizaje del desarrollo de malware con el objetivo final de ralizar bypass de un EDR
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker